let character = "Hello";
let count = 8;
let rows = ["Naomi", "Quincy", "CamperChan"];
rows.push("freeCodeCamp");
let popped = rows.pop();
console.log(popped);
console.log(rows);
let pushed = rows.push("freeCodeCamp");
console.log(pushed);
console.log(rows);
